// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function ClearFinishedTasks() {
  return window['go']['main']['App']['ClearFinishedTasks']();
}

export function DeleteAllTasks() {
  return window['go']['main']['App']['DeleteAllTasks']();
}

export function DeleteTaskByID(arg1) {
  return window['go']['main']['App']['DeleteTaskByID'](arg1);
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['SetTaskStatus'](arg1, arg2);
}
