// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';

export function AddTask(arg1:string):Promise<utils.Task>;

export function ClearFinishedTasks():Promise<void>;

export function DeleteAllTasks():Promise<void>;

export function DeleteTaskByID(arg1:string):Promise<void>;

export function GetTasks():Promise<Array<utils.Task>>;

export function Greet(arg1:string):Promise<string>;

export function SetTaskStatus(arg1:string,arg2:utils.TaskStatus):Promise<void>;
