// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';

export function AddTodo(arg1:string):Promise<utils.Todo>;

export function ClearFinishedTasks():Promise<void>;

export function DeleteAllTasks():Promise<void>;

export function DeleteTaskByID(arg1:string):Promise<void>;

export function GetTodos():Promise<Array<utils.Todo>>;

export function Greet(arg1:string):Promise<string>;

export function SetTaskStatus(arg1:string,arg2:utils.TodoStatus):Promise<void>;
